# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json
name: p1-big-bang-template
metadata:
  template: p1-big-bang-template@0.0.1-beta
hooks:
  preprovision:
    interactive: true
    shell: sh
    run: chmod -R +x infra/azure/azd-hooks/*.sh && infra/azure/azd-hooks/preprovision.sh # Registers any required features on the subscription
  postprovision:
    interactive: true
    shell: sh
    run: infra/azure/azd-hooks/postprovision.sh
infra:
  provider: bicep
  path: infra/azure
  module: main
services:
  app:
    project: ./src/app/code # path to your "app" project, change to the appropriate path
    language: js # language of your app, change to the appropriate language
    host: aks # deployment target
    k8s:
      deploymentPath: ../manifests # relative path to your Kubernetes manifests folder from the project folder
pipeline:
  provider: github